---
title: "DATA 624 Homework 1"
format: html
author: "Kevin Havis"
---

```{r}
library(tidyverse)
library(fpp3)
library(tsibble)
library(ggplot2)
library(tsibbledata)
```

# Homework 1


## Exercise 2.1

```{r}
# https://otexts.com/fpp3/graphics-exercises.html

?aus_production # Half hourly
?lynx # Annual
?gafa_stock # trading days
?vic_elec # Half hourly
```

```{r}
# Autoplot each data by the specified feature
autoplot(aus_production, Bricks)
autoplot(pelt, Lynx)
autoplot(gafa_stock, Close)
autoplot(vic_elec, Demand)
```

## Exercise 2.2

```{r}
# I can groupby and take the max to find top close days for each stock
top_stock_days <- gafa_stock |> 
  group_by(Symbol) |> 
  slice_max(Close, n=1) # Gets the max for each element I've grouped (Symbol)

head(top_stock_days)
```

## Exercise 2.3

```{r}
# Read data from URL
tute1 <- read_csv("https://otexts.com/fpp3/extrafiles/tute1.csv")
head(tute1)
```
```{r}
# Convert to tsibble
mytimeseries <- tute1 |>
  mutate(Quarter = yearquarter(Quarter)) |> # Formats date to yearquarter type
  as_tsibble(index = Quarter) # Converts to tsibble
head(mytimeseries)
```

```{r}
# Plot the timeseries
mytimeseries |>
  pivot_longer(-Quarter) |> # Viz friendly format
  ggplot(aes(x = Quarter, y = value, colour = name)) +
  geom_line() +
  facet_grid(name ~ ., scales = "free_y") # Sets a facet for each column
```

## Exercise 2.4

```{r}
# Get the US Gas dataset
install.packages("USgas")
library(USgas)
```

```{r}
head(usgas)
```


```{r}
# Plot the New England states
ne_gas <- usgas |> 
  mutate(Year = year(date)) |> 
  group_by(Year, state) |>
  summarize(y_sum = sum(y)) |> 
  filter(state %in% c("Maine", "Vermont", "New Hampshire", "Massachusetts", "Connecticut","Rhode Island")) |> 
  as_tsibble(index=Year, key=state)

head(ne_gas)
```

```{r}
# Plot the data
ne_gas |>
  ggplot(aes(x = Year, y = y_sum, colour = state)) +
  geom_line() +
  facet_grid(state ~ ., scales = "free_y")
```

## Exercise 2.5

```{r}
# Load the tourism data from the package
# Our reference point
head(tsibble::tourism)
```


```{r}
# Download the example tourism file
library(readxl)
my_tourism <- read_excel("~/projects/data_624/assignments/tourism.xlsx")
head(my_tourism)
```

```{r}
# Match downloaded tourism data to package data
# Just need to convert the char Quarter to yearquarter
my_tourism <- my_tourism |>
  mutate(Quarter = yearquarter(Quarter))

head(my_tourism)
```

```{r}
# Find the most amount of flights by Purpose and Region
my_tourism |>
  group_by(Region, Purpose) |> 
  summarize(total_trips = sum(Trips)) |> 
  arrange(desc(total_trips))

# It's Sydney!
```

```{r}
# Group by just state and trips
my_tourism |> 
  group_by(State) |> 
  summarize(total_trips = sum(Trips)) |> 
  arrange(desc(total_trips))
```

## Exercise 2.6

```{r}
# Get the aus_arrival data from the package
arrival_data <- fpp3::aus_arrivals
```

```{r}
# Try autoplot
autoplot(arrival_data)
```
```{r}
# Try seasons
library(feasts)
gg_season(arrival_data)
```

```{r}
# Try subseries
gg_subseries(arrival_data)
```

